"""
Initial empty migration for project (autogenerated placeholder).

Revision ID: 0001_initial
Revises: 
Create Date: 2026-01-28

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # No-op initial migration — schema is managed via models/Alembic autogenerate for future revisions.
    pass


def downgrade():
    pass
